# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 3d-ldm-ingress
  namespace: 3d-ldm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - 3d-ldm-api.yourdomain.com
    secretName: 3d-ldm-tls
  rules:
  - host: 3d-ldm-api.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 3d-ldm-api-service
            port:
              number: 80
---
# NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: 3d-ldm-network-policy
  namespace: 3d-ldm
spec:
  podSelector:
    matchLabels:
      app: 3d-ldm-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nginx-ingress
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: 3d-ldm-metrics
  namespace: 3d-ldm
  labels:
    app: 3d-ldm-api
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: 3d-ldm-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: 3d-ldm-pdb
  namespace: 3d-ldm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: 3d-ldm-api