name: 3d-ldm-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  
  # Core ML libraries
  - numpy>=1.21.0
  - scipy>=1.9.0
  - scikit-learn>=1.3.0
  - pandas>=1.5.0
  
  # Medical imaging
  - nibabel>=5.0.0
  - simpleitk>=2.2.0
  
  # Visualization and monitoring
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tensorboard>=2.13.0
  - tqdm>=4.64.0
  
  # Configuration
  - pyyaml>=6.0
  - omegaconf>=2.3.0
  
  # Azure ML and MLOps
  - pip
  
  - pip:
    # MONAI
    - monai>=1.3.0
    
    # Azure ML SDK v2
    - azure-ai-ml>=1.11.0
    - azure-identity>=1.14.0
    - azure-storage-blob>=12.17.0
    
    # MLflow for experiment tracking
    - mlflow>=2.7.0
    - mlflow-skinny
    
    # Additional ML utilities
    - timm>=0.9.0
    - transformers>=4.30.0
    - accelerate>=0.20.0
    
    # Distributed training
    - deepspeed>=0.10.0
    
    # Model optimization
    - onnx>=1.14.0
    - onnxruntime-gpu>=1.16.0
    
    # API and web services
    - fastapi>=0.103.0
    - uvicorn>=0.23.0
    - pydantic>=2.4.0
    
    # Monitoring and logging
    - prometheus-client>=0.17.0
    - py-spy>=0.3.14
    
    # Development tools
    - pytest>=7.4.0
    - black>=23.7.0
    - flake8>=6.0.0
    - pre-commit>=3.4.0